schema: "classroom50/repo-config/v1"
classroom: "swdevprac2-69-1"
assignment: "a06-swdevprac2-69-1"
secret: "cf2djm54"
owner:
  username: "piranatw"
  id: 116284366
  accepted_at: "2026-09-16T16:39:40Z"
source:
  owner: "SWDevPrac2-69-1"
  owner_id: 312147402
  repo: "2110507_a06_starter"
  branch: "main"
